### ISSUE TITLE
Nao entendi o n - ctd -1.

### ISSUE THREAD

**Issue by gabryelsouzz** [unfav-ri/Faculdade---Eng-da-comp#1]
Opa, mano. Sou iniciante na area de programação competitiva e emperrei nessa questão da maratona de 2022. Então fui pesquisar para ver se alguem poderia ajudar ou se teria alguma explicação no git hub e achei esse seu código. Poderia explicar a logica da linha que tem " n - ctd - 1 ", por favor?

**Comment by unfav-ri** [comment]
Bem-vindo! Poderia me fornecer mais detalhes sobre qual código utilizou como referência?

**Comment by gabryelsouzz** [comment]
Opa, me perdoa achei que o código em si ja seria automaticamente referenciado pelo github. Eu estava falando do codigo "Deslocando particulas" que esta na pasta "Aula 7". Aqui o path: "Programação estruturada 2024-01/Aula 7/Deslocando_Particulas.c"

**Comment by unfav-ri** [comment]
Certo. Primeiro, vamos entender as variáveis que estão coletando informações:

- **N**: representa a dimensão do quadrado.
- **cnt**: quantidade de vezes que conseguimos dividir **x** e **y** antes de torná-los ímpares. Com isso, ele consegue indicar quantas ativações foram necessárias para chegar ao ponto médio entre a posição inicial e a desejada.
- **x** e **y**: são as coordenadas das partículas.

Portanto:

**n - cnt - 1**: subtrai a quantidade de ativações já feitas **(cnt)** do número total de ativações possíveis **(n)**. Além disso, é **subtraído 1** para compensar o fato de que a posição inicial já foi considerada no **loop for(cnt = 0 ...)**, então não precisamos contar novamente.

**Exemplo:**

**Entrada: 4 3 1**

Aqui, **N** = **4**, **x** = **3** e **y** = **1**.

A posição inicial da partícula é **(15, 15)** e a posição desejada é **(3, 1)**.

Três ativações são necessárias para mover a partícula para a posição desejada.

**Saída: 3**

Esses exemplos ilustram como a entrada de valores de **N**, **x** e **y** afeta o número mínimo de ativações necessárias para mover a partícula para a posição desejada.

Observação: A posição inicial da partícula é calculada como **(2^N - 1, 2^N - 1)**, onde **N** é a dimensão do quadrado. No exemplo dado, **N = 4**. Portanto, a posição inicial da partícula seria **(2^4 - 1, 2^4 - 1) = (15, 15)**.

**Comment by gabryelsouzz** [comment]
Cara, tu não tem noção de como tu ajudou, de verdade. Agora eu entendi legal como que funciona essa solução e vai ser grande ajuda para mim. Muito obrigado. Todo o sucesso do mundo para você.
